FROM python:3.10.7-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1

RUN apt update && apt -y install libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY code /code/
WORKDIR /code
